# Generated by Django 3.1 on 2021-03-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_products', models.IntegerField(default=0, verbose_name='bought')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.client')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
            ],
        ),
    ]
