# Generated by Django 3.1 on 2021-03-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20, verbose_name='Name')),
                ('client_lastname', models.CharField(max_length=20, verbose_name='Lastname')),
                ('client_address', models.CharField(max_length=50, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Username')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.client')),
            ],
        ),
    ]
