# Generated by Django 3.1 on 2021-03-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the supplier company', max_length=50, verbose_name='Company name')),
                ('company_line', models.CharField(help_text='Company line', max_length=50, verbose_name='Company line')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name', max_length=50, verbose_name='Product name')),
                ('product_description', models.TextField(help_text='Product description', max_length=200, verbose_name='product Description')),
                ('stock_product', models.IntegerField(default=0, verbose_name='Stock')),
                ('product_price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Price')),
                ('id_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.supplier')),
            ],
        ),
    ]
